class

diff --git a/.github/workflows/session5-classwork.yml b/.github/workflows/session5-classwork.yml
--- a/.github/workflows/session5-classwork.yml
+++ b/.github/workflows/session5-classwork.yml
@@ -3,7 +3,6 @@ on:
   push:
     branches:
       - main
-      - session5-classwork
     paths:
       - '.github/workflows/main.yml'
   pull_request:
@@ -34,27 +33,25 @@ jobs:
   job-b:
     runs-on: ubuntu-latest
     needs: job-a
-    if: github.ref == 'refs/heads/session5-classwork'
+    if: ${{ github.ref == 'refs/heads/session5-classwork' }}
     steps:
-      - name: Checkout repo
+      - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Setup Python
-        id: python_setup
+      - name: Set up Python
         uses: actions/setup-python@v5
+        id: setup-python
         with:
-          python-version: ${{env.PYTHON_VERSION}}
-
-      - name: Run Python Script
-        id: python_run
-        if: ${{ steps.python_setup.outcome == 'success' }}
-        working-directory: scripts
-        run: |
-          python simple_python.py
-          echo "Hey, it was executed successfully"
-          exit 1
+          python-version: ${{ env.PYTHON_VERSION }}
       
-      - name: Echo if the previous step is failed
-        if: ${{ failure() && steps.python_run.outcome == 'failure' }}
+      - name: Run script
+        working-directory: scripts
+        id: run-script
+        if: ${{ steps.setup-python.outcome == 'success' }}
         run: |
-          echo "Failed: ${{steps.python_run.outcome}}"
+          python run.py 
+          exit 1
+      - name: echo previous step failed 
+        if: ${{ failure() && steps.run-script.outcome == 'failure' }}
+        run: |
+          echo "The previous step failed, but we are continuing."
